name: main
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./build.sh
      timeout-minutes: 15
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
        if-no-files-found: error

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - run: ls -al
    - run: ls -al dist
    - if: "github.ref_type == 'tag'"
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.pdf
        name: 『自分だけのフェディバースのマイクロブログを作ろう！』${{ github.ref_name }}版
        fail_on_unmatched_files: true
